# Generated by Django 4.2.4 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_availability_vehicle_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='advance_paid',
            field=models.FloatField(default=0),
        ),
    ]
