# Generated by Django 4.2.4 on 2025-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_rental_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
