# Generated by Django 4.2.4 on 2025-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rental_is_fully_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
