# Generated by Django 4.2.4 on 2025-03-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='advance_paid',
        ),
    ]
